### ISSUE TITLE
Running custom Ruby script as a build command on Netlify leads to a gem load error

### ISSUE THREAD

**Issue by vladyio** [netlify/build-image#290]
_I am really sorry if it's a wrong place to ask about this_

I have a Ruby script that generates HTML from Markdown. I tried to execute the following build command: 

```
ruby blog.rb
```

This command would work locally (I mean without Docker image), but it doesn't work on Netlify. 

It throws a LoadError regarding gems from Gemfile.  Here's the log I get:

<details>
<pre>
9:55:18 PM: Started restoring cached ruby gems
9:55:18 PM: Finished restoring cached ruby gems
9:55:18 PM: Installing gem bundle
9:55:21 PM: Fetching gem metadata from https://rubygems.org/
9:55:21 PM: .
9:55:21 PM: Using bundler 2.0.1
9:55:21 PM: Fetching kramdown 2.1.0
9:55:21 PM: Installing kramdown 2.1.0
9:55:21 PM: Fetching readingtime 0.4.0
9:55:21 PM: Installing readingtime 0.4.0
9:55:21 PM: Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
9:55:21 PM: Bundled gems are installed into `/opt/build/cache/bundle`
9:55:21 PM: Gem bundle installed
 [ ... ]
9:55:22 PM: Executing user command: ruby blog.rb
9:55:22 PM: /opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- kramdown (LoadError)
9:55:22 PM:     from /opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
9:55:22 PM:     from blog.rb:4:in `<main>'
9:55:22 PM: Caching artifacts
9:55:22 PM: Started saving ruby gems
9:55:22 PM: Finished saving ruby gems
 [ ... ]
9:55:24 PM: Error running command: Build script returned non-zero exit code: 1
9:55:24 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:55:24 PM: Failing build: Failed to build site
</pre>
</details>

`.ruby-version` (`2.6.2`), `.ruby-gemset`, `Gemfile/Gemfile.lock` files are all properly set up in the project directory.

**Comment by vladyio** [comment]
Issue solved, `bundle exec` before `ruby blog.rb` did the thing.
