### ISSUE TITLE
Same codebase stopped compiling in version 4.13

### ISSUE THREAD

**Issue by caiquecamargo** [netlify/build-image#852]
**Is your build failing?**

yes

**Describe the bug**

Same codebase stopped compiling in version 4.13. Noticed that the monorepo workspace in not detected.

**To Reproduce**

1. https://app.netlify.com/sites/numpro-app/deploys/634b59c19d66df0008cad31f
2. https://app.netlify.com/sites/numpro-app/deploys/634dee6bf947e352ee2d46dc

Two differents builds to the same codebase (i have to force the re-build due to not detecting changes). First work, second not. The only difference between then is the image version.

**Configuration**
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"
  VITE_GRAPHQL_ENDPOINT = ***


[context.production.environment]
  VITE_REDIRECT_URL = ***

[context.branch-deploy.environment]
  VITE_REDIRECT_URL = ***
```

**Expected behavior**

Same result as there is no breaking change

**Build Output**

build working log

```
10:09:21 PM: Build ready to start
10:09:32 PM: build-image version: 9289b698a503f132b265bd089ab40ce1d6f9e65e (focal)
10:09:32 PM: build-image tag: v4.12.0
10:09:32 PM: buildbot version: 2510ae842d7cc96532da2c05a74ba836f3e7f056
10:09:32 PM: Fetching cached dependencies
10:09:32 PM: Starting to download cache of 214.7MB
10:09:34 PM: Finished downloading cache in 1.940091439s
10:09:34 PM: Starting to extract cache
10:09:36 PM: Finished extracting cache in 2.300280781s
10:09:36 PM: Finished fetching cache in 4.32504567s
10:09:36 PM: Starting to prepare the repo for build
10:09:36 PM: Preparing Git Reference refs/heads/main
10:09:37 PM: Parsing package.json dependencies
10:09:38 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'client/app/dist' versus 'dist' in the Netlify UI
10:09:38 PM: Starting build script
10:09:38 PM: Installing dependencies
10:09:38 PM: Python version set to 2.7
10:09:39 PM: Started restoring cached node version
10:09:40 PM: Finished restoring cached node version
10:09:40 PM: v16.18.0 is already installed.
10:09:41 PM: Now using node v16.18.0 (npm v8.19.2)
10:09:41 PM: Started restoring cached build plugins
10:09:41 PM: Finished restoring cached build plugins
10:09:41 PM: Attempting ruby version 2.7.2, read from environment
10:09:41 PM: Using ruby version 2.7.2
10:09:42 PM: Using PHP version 8.0
10:09:42 PM: npm workspaces detected     // I noticed changes here
10:09:42 PM: Started restoring workspace root node modules
10:09:42 PM: Finished restoring workspace root node modules
10:09:42 PM: Installing NPM modules using NPM version 8.19.2
10:09:42 PM: npm ERR! code ENOWORKSPACES
10:09:42 PM: npm ERR! This command does not support workspaces.
10:09:42 PM: npm ERR! A complete log of this run can be found in:
10:09:42 PM: npm ERR!     /opt/buildhome/.npm/_logs/2022-10-16T01_09_42_744Z-debug-0.log
10:10:47 PM: changed 10 packages, and audited 435 packages in 1m
10:10:47 PM: 51 packages are looking for funding
10:10:47 PM:   run `npm fund` for details
10:10:47 PM: found 0 vulnerabilities
10:10:47 PM: NPM modules installed
10:10:47 PM: Started restoring cached go cache
10:10:47 PM: Finished restoring cached go cache
10:10:47 PM: Installing Go version 1.17 (requested 1.17)
10:10:51 PM: unset GOOS;
10:10:51 PM: unset GOARCH;
10:10:51 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
10:10:51 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
10:10:51 PM: go version >&2;
10:10:51 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
10:10:51 PM: go version go1.17 linux/amd64
10:10:51 PM: Installing missing commands
10:10:51 PM: Verify run directory
10:10:53 PM: ​
10:10:53 PM: ────────────────────────────────────────────────────────────────
10:10:53 PM:   Netlify Build                                                 
10:10:53 PM: ────────────────────────────────────────────────────────────────
10:10:53 PM: ​
10:10:53 PM: ❯ Version
10:10:53 PM:   @netlify/build 27.20.6
10:10:53 PM: ​
10:10:53 PM: ❯ Flags
10:10:53 PM:   baseRelDir: true
10:10:53 PM:   buildId: 634b59c19d66df0008cad31d
10:10:53 PM:   deployId: 634b59c19d66df0008cad31f
10:10:53 PM: ​
10:10:53 PM: ❯ Current directory
10:10:53 PM:   /opt/build/repo/client/app
10:10:53 PM: ​
10:10:53 PM: ❯ Config file
10:10:53 PM:   /opt/build/repo/client/app/netlify.toml
10:10:53 PM: ​
10:10:53 PM: ❯ Context
10:10:53 PM:   production
10:10:53 PM: ​
10:10:53 PM: ────────────────────────────────────────────────────────────────
10:10:53 PM:   1. Build command from Netlify app                             
10:10:53 PM: ────────────────────────────────────────────────────────────────
10:10:53 PM: ​
10:10:53 PM: $ yarn build
10:10:53 PM: yarn run v1.22.19
( ... )
10:11:21 PM: Done in 28.33s.
10:11:21 PM: ​
10:11:21 PM: (build.command completed in 28.4s)
10:11:21 PM: ​
10:11:21 PM: ────────────────────────────────────────────────────────────────
10:11:21 PM:   2. Deploy site                                                
10:11:21 PM: ────────────────────────────────────────────────────────────────
10:11:21 PM: ​
10:11:21 PM: Starting to deploy site from 'client/app/dist'
10:11:21 PM: Creating deploy tree 
10:11:21 PM: Creating deploy upload records
10:11:22 PM: 95 new files to upload
10:11:22 PM: 0 new functions to upload
10:11:23 PM: Site deploy was successfully initiated
10:11:23 PM: ​
10:11:23 PM: (Deploy site completed in 1.4s)
10:11:23 PM: ​
10:11:23 PM: ────────────────────────────────────────────────────────────────
10:11:23 PM:   Netlify Build Complete                                        
10:11:23 PM: ────────────────────────────────────────────────────────────────
10:11:23 PM: ​
10:11:23 PM: (Netlify Build completed in 29.9s)
10:11:23 PM: Starting post processing
10:11:23 PM: Post processing - HTML
10:11:23 PM: Caching artifacts
10:11:23 PM: Started saving workspace root node modules
10:11:23 PM: Finished saving workspace root node modules
10:11:23 PM: Started saving build plugins
10:11:23 PM: Finished saving build plugins
10:11:23 PM: Started saving pip cache
10:11:23 PM: Finished saving pip cache
10:11:23 PM: Started saving emacs cask dependencies
10:11:23 PM: Finished saving emacs cask dependencies
10:11:23 PM: Started saving maven dependencies
10:11:23 PM: Finished saving maven dependencies
10:11:23 PM: Started saving boot dependencies
10:11:23 PM: Post processing - header rules
10:11:23 PM: Finished saving boot dependencies
10:11:23 PM: Started saving rust rustup cache
10:11:23 PM: Finished saving rust rustup cache
10:11:23 PM: Started saving go dependencies
10:11:23 PM: Finished saving go dependencies
10:11:23 PM: Build script success
10:11:23 PM: Post processing - redirect rules
10:11:23 PM: Post processing done
10:11:25 PM: Uploading Cache of size 214.6MB
10:11:26 PM: Site is live ✨
10:11:26 PM: Finished processing build request in 1m54.598256656s
```

build not working log

```
9:08:11 PM: Build ready to start
9:08:13 PM: build-image version: d05976bd3309b73a86eaa327bf80e105ff13f5e4 (focal)
9:08:13 PM: build-image tag: v4.13.0
9:08:13 PM: buildbot version: e88e269d333bbe24fbc3ced8a202391bde1e012e
9:08:13 PM: Building without cache
9:08:13 PM: Starting to prepare the repo for build
9:08:13 PM: No cached dependencies found. Cloning fresh repo
9:08:13 PM: git clone https://github.com/caiquecamargo/numpro
9:08:14 PM: Preparing Git Reference refs/heads/main
9:08:14 PM: Parsing package.json dependencies
9:08:15 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'client/app/dist' versus 'dist' in the Netlify UI
9:08:16 PM: Starting build script
9:08:16 PM: Installing dependencies
9:08:16 PM: Python version set to 2.7
9:08:16 PM: v16.18.0 is already installed.
9:08:17 PM: Now using node v16.18.0 (npm v8.19.2)
9:08:17 PM: Enabling node corepack
9:08:17 PM: Started restoring cached build plugins
9:08:17 PM: Finished restoring cached build plugins
9:08:17 PM: Attempting ruby version 2.7.2, read from environment
9:08:17 PM: Using ruby version 2.7.2
9:08:18 PM: Using PHP version 8.0
9:08:18 PM: No npm workspaces detected   // I noticed changes here
9:08:18 PM: Started restoring cached node modules
9:08:18 PM: Finished restoring cached node modules
9:08:19 PM: Installing NPM modules using NPM version 8.19.2
9:09:29 PM: npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
9:09:29 PM: added 380 packages, and audited 383 packages in 1m
9:09:29 PM: 51 packages are looking for funding
9:09:29 PM:   run `npm fund` for details
9:09:29 PM: found 0 vulnerabilities
9:09:29 PM: NPM modules installed
9:09:30 PM: Started restoring cached go cache
9:09:30 PM: Finished restoring cached go cache
9:09:30 PM: Installing Go version 1.17 (requested 1.17)
9:09:35 PM: unset GOOS;
9:09:35 PM: unset GOARCH;
9:09:35 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
9:09:35 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
9:09:35 PM: go version >&2;
9:09:35 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
9:09:35 PM: go version go1.17 linux/amd64
9:09:35 PM: Installing missing commands
9:09:35 PM: Verify run directory
9:09:36 PM: ​
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM:   Netlify Build                                                 
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM: ​
9:09:36 PM: ❯ Version
9:09:36 PM:   @netlify/build 27.20.6
9:09:36 PM: ​
9:09:36 PM: ❯ Flags
9:09:36 PM:   baseRelDir: true
9:09:36 PM:   buildId: 634dee6bf947e352ee2d46da
9:09:36 PM:   deployId: 634dee6bf947e352ee2d46dc
9:09:36 PM: ​
9:09:36 PM: ❯ Current directory
9:09:36 PM:   /opt/build/repo/client/app
9:09:36 PM: ​
9:09:36 PM: ❯ Config file
9:09:36 PM:   /opt/build/repo/client/app/netlify.toml
9:09:36 PM: ​
9:09:36 PM: ❯ Context
9:09:36 PM:   production
9:09:36 PM: ​
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM:   1. Build command from Netlify app                             
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM: ​
9:09:36 PM: $ yarn build
9:09:36 PM: Internal Error: @numpro/monorepo@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile    at TR.getCandidates (/opt/buildhome/.cache/node/corepack/yarn/3.2.2/yarn.js:435:5226)
9:09:36 PM:     at wd.getCandidates (/opt/buildhome/.cache/node/corepack/yarn/3.2.2/yarn.js:391:1281)
9:09:36 PM:     at /opt/buildhome/.cache/node/corepack/yarn/3.2.2/yarn.js:439:7764
9:09:36 PM:     at Lg (/opt/buildhome/.cache/node/corepack/yarn/3.2.2/yarn.js:390:11154)
9:09:36 PM:     at ce (/opt/buildhome/.cache/node/corepack/yarn/3.2.2/yarn.js:439:7744)
9:09:36 PM: ​
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM:   "build.command" failed                                        
9:09:36 PM: ────────────────────────────────────────────────────────────────
9:09:36 PM: ​
9:09:36 PM:   Error message
9:09:36 PM:   Command failed with exit code 1: yarn build (https://ntl.fyi/exit-code-1)
9:09:36 PM: ​
9:09:36 PM:   Error location
9:09:36 PM:   In Build command from Netlify app:
9:09:36 PM:   yarn build
9:09:36 PM: ​
9:09:36 PM:   Resolved config
9:09:36 PM:   build:
9:09:36 PM:     base: /opt/build/repo/client/app
9:09:36 PM:     command: yarn build
9:09:36 PM:     commandOrigin: ui
9:09:36 PM:     environment:
9:09:36 PM:       - VITE_GRAPHQL_ENDPOINT
9:09:36 PM:       - VITE_REDIRECT_URL
9:09:36 PM:       - NODE_VERSION
9:09:36 PM:     publish: /opt/build/repo/client/app/dist
9:09:36 PM:     publishOrigin: ui
9:09:36 PM:   redirects:
9:09:37 PM:     - from: /*      status: 200      to: /index.html  redirectsOrigin: configCaching artifacts
9:09:37 PM: Started saving node modules
9:09:37 PM: Finished saving node modules
9:09:37 PM: Started saving build plugins
9:09:37 PM: Finished saving build plugins
9:09:37 PM: Started saving pip cache
9:09:37 PM: Finished saving pip cache
9:09:37 PM: Started saving emacs cask dependencies
9:09:37 PM: Finished saving emacs cask dependencies
9:09:37 PM: Started saving maven dependencies
9:09:37 PM: Finished saving maven dependencies
9:09:37 PM: Started saving boot dependencies
9:09:37 PM: Finished saving boot dependencies
9:09:37 PM: Started saving rust rustup cache
9:09:37 PM: Finished saving rust rustup cache
9:09:37 PM: Started saving go dependencies
9:09:37 PM: Finished saving go dependencies
9:09:39 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:09:39 PM: Creating deploy upload records
9:09:40 PM: Failing build: Failed to build site
9:09:40 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:09:40 PM: Finished processing build request in 1m27.015064918s

```

**Additional context**

The repository is a monorepo, using yarn version 1.22.19 and I noticed that the last update didn't compile, it was just css style changes, which normally wouldn't cause problems. I went back the repository to a previous commit that had already been compiled and it happened that it didn't compile this time.

Something I noticed in the logs is the non-detection of npm workspaces, normally I had the message "npm workspaces detected" which is now "No npm workspaces detected"

**Comment by kitop** [comment]
@caiquecamargo there were some changes to the build image to add native support for pnpm. This might have affected your build, since it changed to use corepack for yarn when available, and it seems like it affected the version and workspace detection.

We're looking at it!

**Comment by lukasholzer** [comment]
@caiquecamargo the issue is, that previously we where ignoring the `packageManager` field in the `package.json` (which I guess you have configured)

Now with the newly introduced feature of adding PNPM + node corepack see: https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/

node corepack respects the `packageManager` field where I guess you have configured it to have `yarn@3.2.2` and therefore tries to run the command with it.

As we currently not officially supporting yarn berry workspaces (Already in progress) this caused your build to fail (The workspace detection command changed there)

**Comment by lukasholzer** [comment]
@caiquecamargo As a workaround to get it working setting the environment variable for your builds `NETLIFY_USE_YARN=true` should do a fix

**Comment by caiquecamargo** [comment]
> 

Yes, I was using yarn '3.2.2' before, but I had some problems using it with Netlify and I rollback to yarn '1.22.19'.

The `packageManager` entry in package.json was pointing to yarn in version `3` and that ended up causing the issue. I removed the entry and the build started working again. 

I didn't get to set the environment variable `NETLIFY_USE_YARN=true`, so I don't know if it would work.

With that I think I can consider this issue closed. Thanks!!!
